name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write                # permite push na gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json   # <-- lockfile correto

      - name: Install dependencies
        working-directory: ./docs                        # <-- entra em docs
        run: npm ci

      - name: Build site
        working-directory: ./docs
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build                      # <-- saída correta
